### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by kenneth** [viacoin/viacoin#18]
```
Traceback (most recent call last):
  File "./contrib/macdeploy/macdeployqtplus", line 799, in <module>
    m = re.search("/Volumes/(.+$)", output)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Viacoin-Core.dmg] Error 1
```

**Comment by romanornr** [comment]
Might be solved in @nitronick600 pull request https://github.com/viacoin/viacoin/pull/17
However you can use the Mac binaries: https://github.com/viacoin/viacoin/releases

**Comment by kenneth** [comment]
@romanornr  meet a new link error! 

```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by romanornr** [comment]
Oh well. Core 0.15 will be released soon & the problem will be gone.

For now you can use the Mac binaries so you don't have to compile it yourself.

**Comment by romanornr** [comment]
should be solved now
